plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-spaceship
  - jekyll/scholar
  - jekyll-mentions
  - jekyll-gist
  - jemoji

url: "https://colewilson.xyz"
permalink: /:title/
collections:
  projects:
    output: true
  pages:
    output: true
    permalink: /:name
  links:
    output: false
  slideshows:
    output: true
    premalink: /slides/:name

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: slideshows
    values:
      layout: slideshow
