url: "https://example.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-feed
  
permalink: /:title/
collections:
  projects:
    output: true
  pages:
    output: true
    permalink: /:name
  links:
    output: false
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
