url: "https://colewilson.xyz"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  
permalink: /:title/
collections:
  projects:
    output: true
  pages:
    output: true
    permalink: /:name
  links:
    output: false
  slideshows:
    output: true
    premalink: /slides/:name

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
#
