# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "."
  publish = "_site/"
  command = "python3 build.py;echo -e '---\nj: true\n---' | cat - netlify.toml > n.txt; cp n.txt netlify.toml;jekyll build"
  functions = "_functions/"

[context.deploy-preview]
  publish = "_site/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    X-Super-Duper-Secret-Word = "gnomon"

[[redirects]]
# Force HTTPS
  from = "http://colewilson.xyz/*"
  to = "https://colewilson.xyz/:splat"
  status = 301
  force = true
  
# START URL SHORTENER
#{% for url in site.links %}
#  {% if url.countries or url.languages %} 
#    {% for country in url.countries %}
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}"
  to = "{{url.u}}"
  status = 302
  force = true
  conditions = {Country = ["{{country}}"]}
#{% endfor %}
#    {% for language in url.languages %}
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}"
  to = "{{url.u}}"
  status = 302
  force = true
  conditions = {Language = ["{{language}}"]}
#    {% endfor %}
#  {% else %}
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}"
  to = "{{url.u}}"
  status = 302
  force = true
#{% endif %}
#{% endfor %}
[[redirects]]
  from = "https://u.colewilson.xyz/*"
  to = "https://colewilson.xyz/404.html"
  status = 404
  force = true

# END URL SHORTENER
