[build]
base = "."
publish = "_site/"
command = "python3 _tools/main.py;echo -e '---\nj: true\n---' | cat - netlify.toml > n.txt; cp n.txt netlify.toml;cp assets/*.css m.css;jekyll build"
functions = "_functions/"
[context.deploy-preview]
publish = "_site/"
[[headers]]
for = "/*"
[headers.values]
X-Random = "Goats are funny"
[[headers]]
for = "/n.txt"
[headers.values]
WWW-Authenticate = "Basic"

[[redirects]]
from = "http://colewilson.xyz/*"
to = "https://colewilson.xyz/:splat"
status = 301
force = true
[[redirects]]
from = "https://colewilson.xyz/proxy/cmg/*"
to = "https://www.coolmathgames.com/:splat"
status = 200
force = true

[[redirects]]
from = "https://colewilson.netlify.app/*"
to = "https://colewilson.xyz/:splat"
status = 301
force = true
#############
#{%- for url in site.links -%}
#{%- if url.password -%}
#
[[redirects]]
from = "https://{{url.domain}}/{{url.key}}/{{ url.password }}"
to = "{{url.u}}"
status = 302
force = true

[[redirects]]
from = "https://{{url.domain}}/{{url.key}}/"
to = "/urls/password.html"
status = 200
force = true
#{%- else -%}
#
[[redirects]]
from = "https://{{url.domain}}/{{url.key}}"
to = "{{url.u}}"
status = 302
force = true
#{%- endif -%}
#{%- endfor -%}
#############
[[redirects]]
from = "https://u.colewilson.xyz/*"
to = "/404.html"
status = 404
force = true
[[redirects]]
from = "https://kreacher.colewilson.xyz/*"
to = "https://kreacher.herokuapp.com/:splat"
status = 200
force = true
