# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "."
  publish = "_site/"
  command = "python3 build.py;jekyll build"
  functions = "_functions/"

[context.deploy-preview]
  publish = "_site/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    X-Super-Duper-Secret-Word = "gnomon"
