---
j: true
---
# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "."
  publish = "_site/"
  command = "python3 build.py;jekyll build"
  functions = "_functions/"

[context.deploy-preview]
  publish = "_site/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    X-Super-Duper-Secret-Word = "gnomon"

[[redirects]]
# Force HTTPS
  from = "http://colewilson.xyz/*"
  to = "https://colewilson.xyz/:splat"
  status = 301
  force = true
  
# START URL SHORTENER
#{% for url in site.links %}
#  {% if url.countries or url.languages %} 
#    {% for country in url.countries %}
[[redirects]]
  from = "/u/{{url.key}}"
  to = "{{url.u}}"
  status = 302
  force = true
  conditions = {Country = ["{{url.country}}"]}
#{% endfor %}
#    {% for language in url.languages %}
[[redirects]]
  from = "/u/{{url.key}}"
  to = "{{url.u}}"
  status = 302
  force = true
  conditions = {Language = ["{{url.language}}"]}
#    {% endfor %}
#  {% else %}
[[redirects]]
  from = "/u/{{url.key}}"
  to = "{{url.u}}"
  status = 302
   force = true
#{% endfor %}
# END URL SHORTENER
