# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "."
  publish = "_site/"
  command = "python3 build.py;jekyll build"
  functions = "_functions/"

[context.deploy-preview]
  publish = "_site/"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 302
  force = true
  # More information at https://docs.netlify.com/routing/redirects/redirect-options/#query-parameters
  query = {id = ":id"}
  conditions = {Language = ["en"], Country = ["US"]}
  # You can also define custom headers within your redirects blocks.
  [redirects.headers]
    X-From = "Cole Wilson"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    X-Super-Duper-Secret-Word = "gnomon"
