# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "."
  publish = "_site/"
  command = "echo -e '---\nj: true\n---' | cat - netlify.toml > n.txt; cp n.txt netlify.toml;jekyll build"
  functions = "_functions/"

[context.deploy-preview]
  publish = "_site/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    X-Random = "Goats are funny"

[[redirects]]
# Force HTTPS
  from = "http://colewilson.xyz/*"
  to = "https://colewilson.xyz/:splat"
  status = 301
  force = true
  
# START URL SHORTENER
#{% for url in site.links %}
#############################################################################################################################################
#{% if url.password %}
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}/{{ url.password }}"
  to = "{{url.u}}"
  status = 301
  force = true
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}/"
  to = "https://{{url.domain}}/urls/password.html"
  status = 200
  force = true
#{% else %}
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}"
  to = "{{url.u}}"
  status = 302
  force = true
#{% endif %}
#############################################################################################################################################
#{% endfor %}
# END URL SHORTENER
[[redirects]]
  from = "https://{{url.domain}}/{{url.key}}/*"
  to = "https://colewilson.xyz/404.html"
  status = 404
  force = true
